=== WiFuchs/garden_opt/src/schemas/garden_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Garden Schema",
  "type": "object",
  "properties": {
    "sqft": {
      "type": "number"
    },
    "greywater": {
      "type": "number"
    },
    "rainwater": {
      "type": "number"
    },
    "weeks": {
      "type": "integer"
    },
    "yields": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "plant": {
            "type": "string"
          },
          "min_yield": {
            "type": "number"
          },
          "max_yield": {
            "type": "number"
          },
          "max_yield_pct": {
            "type": "number"
          }
        },
        "required": ["plant", "min_yield"]
      }
    }
  },
  "required": ["sqft", "greywater", "rainwater", "yields"]
}

=== WiFuchs/garden_opt/case_studies/will_garden/wills_garden.json
{
  "sqft": 100,
  "rainwater": 40,
  "greywater": 40,
  "weeks": 20,
  "yields": [
    {
      "plant": "carrot",
      "min_yield": 10,
      "max_yield_pct": 0.25
    },
    {
      "plant": "tomato",
      "min_yield": 20,
      "max_yield_pct": 0.25,
      "max_yield": 100
    },
    {
      "plant": "corn",
      "min_yield": 10,
      "max_yield_pct": 0.25,
      "max_yield": 40
    },
    {
      "plant": "potato",
      "min_yield": 10,
      "max_yield_pct": 0.25
    },
    {
      "plant": "onion",
      "min_yield": 10,
      "max_yield_pct": 0.25
    }
  ]
}
